# site settings
title: Sydney Micklas
subtitle: 
email: micklas.sydney@gmail.com
description: Welcome to my personal portfolio site.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: United States of America
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/smicklas/
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/sydneymicklas/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
